Theoretical Questions:

Q 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

A key Python library for scientific computing and data analysis, NumPy provides a robust array object that improves Python's ability to handle numerical data. Its main objective is to offer effective and adaptable tools for carrying out logical and mathematical operations on huge datasets. Because NumPy arrays store elements in contiguous memory locations, they minimize overhead and offer vectorized operations—processing complete arrays at once rather than one element at a time—which allow for faster computations than ordinary Python lists.

Among NumPy's benefits are its built-in functions for random number generation, array manipulation, and linear algebra, which make it appropriate for managing multidimensional data, carrying out intricate computations, and developing unique algorithms. NumPy's usefulness in data science, statistics, and machine learning is further increased by its smooth integration with other scientific libraries like SciPy and Pandas. NumPy is essential for advanced numerical analysis and large-scale data processing in Python since it maximizes performance and memory usage.

Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

The arithmetic mean of an array's elements is determined using NumPy's np.mean(), which by default treats each element equally. When a basic average is needed, it's easy to use and perfect. On the other hand, if weights are supplied, np.average() can calculate a weighted average, enabling particular components to have a greater impact on the outcome. np.average() functions similarly to np.mean() in the absence of weights.

For unweighted data or when weights are irrelevant, use np.mean(); it's quicker and easier. When several components should have differing degrees of effect, as in statistical or financial computations including weighted data, use np.average().

Q 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In NumPy, arrays can reversed along various axes using slicing or specific functions like np.flip.

For a 1D array, reversing is straightforward using slicing [::-1].

In [1]:
import numpy as np
arr = np.array([7, 8, 9, 10])
reversed_arr = arr[::-1]  # Output: [10, 9, 8, 7]

For a 2D array, reversing along the rows or columns can be done with slicing or np.flip:

In [ ]:
arr2D = np.array([[1, 2], [3, 4]])
reversed_rows = arr2D[::-1, :]  # Output: [[3, 4], [1, 2]]

Q 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Using the.dtype attribute, which exposes the array's data type, one can ascertain the data type of each element in a NumPy array. Since data types specify how much memory each element takes up, they are essential to memory management and efficiency. For example, int64 needs eight bytes, but int32 uses four. By selecting the smallest appropriate data type, memory use is reduced, enabling larger arrays to fit into memory and accelerating computation. Additionally, since NumPy's vectorized operations are tailored for particular data types, matching data types with operations improves efficiency by accelerating execution.

Q 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

A strong multidimensional container for homogeneous data in NumPy is an ndarray (n-dimensional array), where each member must be of the same data type. Ndarrays enable effective element-wise operations without the need for explicit loops by supporting broadcasting and sophisticated mathematical calculations. Contiguous memory allocation, vectorized operations, and a wealth of data manipulation, reshaping, and slicing capabilities are important elements that contribute to fast speed. In contrast to Python lists, ndarrays are optimized for numerical applications, allow for faster computations, and use less memory. Although lists come in a variety of types, they don't have these efficient operations, which makes them less appropriate for scientific computing and large-scale numerical processing.A strong multidimensional container for homogeneous data in NumPy is an ndarray (n-dimensional array), where each member must be of the same data type. Ndarrays enable effective element-wise operations without the need for explicit loops by supporting broadcasting and sophisticated mathematical calculations. Contiguous memory allocation, vectorized operations, and a wealth of data manipulation, reshaping, and slicing capabilities are important elements that contribute to fast speed. In contrast to Python lists, ndarrays are optimized for numerical applications, allow for faster computations, and use less memory. Although lists come in a variety of types, they don't have these efficient operations, which makes them less appropriate for scientific computing and large-scale numerical processing.

Q 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays' effective memory management and optimized, compiled C code provide notable speed benefits over Python lists for large-scale numerical operations. NumPy arrays, as opposed to lists, provide for quick data access and manipulation by storing elements of the same data type in contiguous memory. Because of this homogeneity, vectorized operations—in which element-wise computations are carried out without the need for Python loops—are possible, which lowers overhead and increases speed. Additionally, NumPy makes use of low-level optimizations like parallel processing and SIMD (Single Instruction, Multiple Data). Significant performance gains are the outcome of these qualities, particularly for high-dimensional data and large-scale calculations that are typical in numerical and scientific applications.

Q 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In NumPy, hstack() and vstack() are used to stack arrays vertically and horizontally, respectively. vstack() combines arrays row-wise, increasing the number of rows, while hstack() stacks them column-wise, increasing the number of columns.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack
v = np.vstack((a, b))  # Output: [[1, 2, 3], [4, 5, 6]]

# Horizontal stack
h = np.hstack((a, b))  # Output: [1, 2, 3, 4, 5, 6]

Q 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

The array flipping functions fliplr() and flipud() in NumPy behave differently. fliplr() reverses the order of elements along the last axis (columns) of a 2D array by flipping it horizontally. For instance, the first column of an array becomes its last. An array with at least two dimensions is needed for this function.

Flipud(), on the other hand, reverses elements along the first axis (rows) to flip an array vertically, making the top row the bottom. Flipud(), in contrast to fliplr(), can be applied to any array that has one or more dimensions. Both approaches reorder elements while preserving the array's form.


Q 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

An array can be divided into designated subarrays using NumPy's array_split() method. Array_split() deals with situations where the array cannot be divided equally, as contrast to split(), which requires splits of the same size. It distributes any residual elements among the original subarrays and generates subarrays of about comparable size. For instance, array_split() will yield subarrays of lengths 4, 3, and 3, respectively, instead of failing if an array of length 10 is divided into three parts. This allows for flexible partitioning without error, which is very helpful when working with data that might not divide equally.

Q 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization in NumPy leverages optimized C code for quicker execution by enabling operations to be applied to whole arrays without the need for explicit loops. This produces short, effective code by avoiding Python's loop overhead. By "stretching" smaller arrays to match larger ones without making duplicate copies, broadcasting makes it possible to perform arithmetic operations on arrays of various shapes. By utilizing underlying optimizations and memory management, vectorization and broadcasting work together to increase computational efficiency, which is crucial for scientific computing and large-scale data processing. These methods enable NumPy to swiftly and efficiently execute intricate array operations with little code.

Practical Questions:

Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [11]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("Transposed Array:\n", transposed_array)

Original Array:
 [[ 7 99 71]
 [ 7 74 18]
 [81 30 28]]
Transposed Array:
 [[ 7  7 81]
 [99 74 30]
 [71 18 28]]


Q 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [12]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)

# Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the 1D array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("1D Array:", array_1d)
print("2x5 Array:\n", array_2x5)
print("5x2 Array:\n", array_5x2)

1D Array: [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [13]:
import numpy as np

# Create a 4x4 array with random floats
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print(array_6x6)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.87934711 0.39369    0.89956449 0.99558456 0.        ]
 [0.         0.41042281 0.28818933 0.09974069 0.11962285 0.        ]
 [0.         0.43125873 0.08990204 0.75868224 0.32830377 0.        ]
 [0.         0.01607701 0.26902756 0.315181   0.12180061 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

---



In [14]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 62, 5)

# Display the array
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


Q 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [15]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
# Use np.char.upper() to apply the upper() method to each element of the array
uppercase = np.char.upper(arr)     # Uppercase
lowercase = np.char.lower(arr)     # Lowercase
titlecase = np.char.title(arr)     # Title case
capitalize = np.char.capitalize(arr)  # Capitalize

# Display the results
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)
print("Capitalize:", capitalize)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']



Q 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [16]:
import numpy as np

# Create a NumPy array of words
words = np.array(['man', 'beautiful', 'red', 'rose'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print(spaced_words)


['m a n' 'b e a u t i f u l' 'r e d' 'r o s e']


Q 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [18]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[4, 6, 9], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [17,  18, 20]])

# Element-wise operations
addition = array1 + array2           # Addition
subtraction = array1 - array2        # Subtraction
multiplication = array1 * array2     # Multiplication
division = array1 / array2           # Division

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[11 14 18]
 [21 23 26]]
Subtraction:
 [[ -3  -2   0]
 [-13 -13 -14]]
Multiplication:
 [[ 28  48  81]
 [ 68  90 120]]
Division:
 [[0.57142857 0.75       1.        ]
 [0.23529412 0.27777778 0.3       ]]


Q 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [20]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [21]:
import numpy as np

# Generate an array of 100 random integers
random_integers = np.random.randint(0, 1001, 100)

# Function to check for prime numbers
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Filter and display prime numbers
prime_numbers = [num for num in random_integers if is_prime(num)]
print(prime_numbers)

[557, 787, 977, 499, 641, 751, 2, 967, 367, 733, 3, 89, 5, 263, 569, 883, 43, 59, 47, 457, 241, 71]


Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [22]:
import numpy as np

# Create an array of daily temperatures for 30 days
temperatures = np.random.randint(0, 35, size=30)

# Reshape the array into a shape compatible with the number of elements
# For example, reshape into 5 weeks of 6 days each (5 * 6 = 30)
weekly_temperatures = temperatures.reshape(5, 6)

# Calculate the average temperature for each week
weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures:", temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [28 33 32 24 10  5 14 10 26 34 13  8  0  7 12 10  8 27 30 33  7  2 21 16
  0  8  3 25  6 34]
Weekly Averages: [22.         17.5        10.66666667 18.16666667 12.66666667]
